// AUTO-GENERATED by scripts/copy-frontpages.mjs — do not edit by hand.
// The 12 most recent "AGI Awareness Post" editions, newest first.
// PNGs are staged (gitignored) in public/frontpages/ from research/front-page/.
export const EDITIONS = [
  "2026-06-15",
  "2026-06-14",
  "2026-06-13",
  "2026-06-12",
  "2026-06-11",
  "2026-06-10",
  "2026-06-09",
  "2026-06-08",
  "2026-06-05",
  "2026-06-04",
  "2026-06-03",
  "2026-06-02"
] as const;
