// AUTO-GENERATED by scripts/gen-screens.mjs — do not edit by hand.
// Real dashboard captures staged in public/screens/. Missing keys fall back
// to a styled mock panel, so the project renders with or without captures.
export type Screen = {src: string; w: number; h: number};

export const SCREENS: Record<string, Screen> = {
  models: {src: "screens/models.png", w: 1440, h: 4000},
  research: {src: "screens/research.png", w: 1440, h: 3976},
  today: {src: "screens/today.png", w: 1440, h: 7146},
  wiki: {src: "screens/wiki.png", w: 1440, h: 5487},
};

export const hasScreen = (k: string): boolean =>
  Object.prototype.hasOwnProperty.call(SCREENS, k);
