// Build the screens manifest (src/screens.ts) from the captured dashboard
// screenshots staged in public/screens/*.png.
//
// Each scene reads SCREENS[key] for {src, w, h}; missing keys fall back to a
// styled mock (see hasScreen), so the project always renders — with or without
// live captures. Dimensions are read straight from the PNG IHDR so scroll math
// in the Pillars scene is exact.
import {readdirSync, statSync, readFileSync, writeFileSync, existsSync, mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const promoRoot = join(__dirname, '..');
const screensDir = join(promoRoot, 'public', 'screens');

function pngSize(file) {
  const buf = readFileSync(file);
  // PNG: 8-byte signature, then IHDR (length+type) at 8; width@16, height@20.
  if (buf.length < 24 || buf.readUInt32BE(0) !== 0x89504e47) return null;
  return {w: buf.readUInt32BE(16), h: buf.readUInt32BE(20)};
}

const camel = (name) =>
  name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

let entries = [];
if (existsSync(screensDir)) {
  entries = readdirSync(screensDir)
    .filter((f) => f.toLowerCase().endsWith('.png'))
    .sort()
    .map((f) => {
      const dims = pngSize(join(screensDir, f));
      if (!dims) return null;
      const key = camel(f.replace(/\.png$/i, ''));
      return {key, src: `screens/${f}`, ...dims};
    })
    .filter(Boolean);
}

const body = entries
  .map((e) => `  ${e.key}: {src: ${JSON.stringify(e.src)}, w: ${e.w}, h: ${e.h}},`)
  .join('\n');

mkdirSync(join(promoRoot, 'src'), {recursive: true});
writeFileSync(
  join(promoRoot, 'src', 'screens.ts'),
  `// AUTO-GENERATED by scripts/gen-screens.mjs — do not edit by hand.\n` +
    `// Real dashboard captures staged in public/screens/. Missing keys fall back\n` +
    `// to a styled mock panel, so the project renders with or without captures.\n` +
    `export type Screen = {src: string; w: number; h: number};\n\n` +
    `export const SCREENS: Record<string, Screen> = {\n${body}\n};\n\n` +
    `export const hasScreen = (k: string): boolean =>\n` +
    `  Object.prototype.hasOwnProperty.call(SCREENS, k);\n`,
);

console.log(`gen-screens: ${entries.length} screens -> ${entries.map((e) => e.key).join(', ') || '(none)'}`);
